### ISSUE TITLE
Bind is giving error for using function in registersimplecondition

### ISSUE THREAD

**Issue by Satyam-16** [BehaviorTree/BehaviorTree.CPP#761] opened 2024-02-01 21:18 UTC
Using input port in condition function by passing parameter BT::TreeNode &self. And trying to use this function by bind is giving error of user type conversion. How to solve this error. Or keep it simple how to use input port in condition function using self as parameter and not in class

**Comment by facontidavide** [comment] 2024-02-01 21:38
Please share a code I can run to reproduce the error. I do not understand what you mean

**Comment by facontidavide** [comment] 2024-02-22 11:08
Closing, since you haven't provided any additional information

**Closed by facontidavide** 2024-02-22 11:08 UTC
Labels: need more info
